In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import japanize_matplotlib
import os

japanize_matplotlib.japanize()
file_path = "../Database/Benesse/1571.csv"

df = pd.read_csv(file_path)
display(df.head())

,PanelID,w1回答フラグ,w2回答フラグ,w3回答フラグ,w4回答フラグ,w5回答フラグ,w6回答フラグ,w7回答フラグ,w1学年,w2学年,...,ds0000000064_w7p,ds0000000066_w7p,ds0000000068_w7p,ds0000000059_w7p,ds0000000061_w7p,ds0000000063_w7p,ds0000000065_w7p,ds0000000067_w7p,ds0000000069_w7p,ds0000000079_w7p
0,1600001,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
1,1600002,6,1,1,1,1,1,4,8888.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600003,6,1,1,1,4,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
3,1600004,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
4,1600005,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0

In [21]:
len(df.index)

29846

In [11]:
label_path = "../Database/Benesse/1571.label.txt"
label = pd.read_table(label_path, encoding="utf-8-sig", header=0)
display(label)

# 4028行目までのデータを使用する
label = label.iloc[2:4028+1]

# Unnamed2 を日本語カラム名に変更する
label = label.rename(columns={
    "Unnamed: 2": "ラベル",
    "Unnamed: 1": "変数"
})
display(label)

                   変数情報 Unnamed: 1 Unnamed: 2
0                    変数         位置        ラベル
1               PanelID          1    PanelID
2               w1回答フラグ          2    w1回答フラグ
3               w2回答フラグ          3    w2回答フラグ
4               w3回答フラグ          4    w3回答フラグ
...                 ...        ...        ...
31725               NaN       8888        非該当
31726               NaN       9999     無回答・不明
31727  ds0000000079_w7p       7777       質問なし
31728               NaN       8888        非該当
31729               NaN       9999     無回答・不明

[31730 rows x 3 columns]

                  変数情報    変数                ラベル
2              w1回答フラグ     2            w1回答フラグ
3              w2回答フラグ     3            w2回答フラグ
4              w3回答フラグ     4            w3回答フラグ
5              w4回答フラグ     5            w4回答フラグ
6              w5回答フラグ     6            w5回答フラグ
...                ...   ...                ...
4024  ds0000000063_w7p  4024        w7p_年齢（第3子）
4025  ds0000000065_w7p  4025        w7p_年齢（第4子）
4026  ds0000000067_w7p  4026        w7p_年齢（第5子）
4027  ds0000000069_w7p  4027        w7p_年齢（第6子）
4028  ds0000000079_w7p  4028  w7p_調査対象のお子様の出生順位

[4027 rows x 3 columns]

In [17]:
rename_map = {
    row["変数情報"]: row["ラベル"]
    for _, row in label.iterrows()
    if pd.notna(row.get("変数情報")) and pd.notna(row.get("ラベル"))
}

In [19]:
df_ja = df.rename(columns=rename_map)

display(df_ja)

,PanelID,w1回答フラグ,w2回答フラグ,w3回答フラグ,w4回答フラグ,w5回答フラグ,w6回答フラグ,w7回答フラグ,w1学年,w2学年,...,w7p_性別（第4子）,w7p_性別（第5子）,w7p_性別（第6子）,w7p_年齢（第1子）,w7p_年齢（第2子）,w7p_年齢（第3子）,w7p_年齢（第4子）,w7p_年齢（第5子）,w7p_年齢（第6子）,w7p_調査対象のお子様の出生順位
0,1600001,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
1,1600002,6,1,1,1,1,1,4,8888.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1600003,6,1,1,1,4,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
3,1600004,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
4,1600005,6,1,1,1,1,1,1,8888.0,1.0,...,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0,7777.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29841,1400368,1,6,6,6,6,6,6,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29842,1502836,1,3,1,6,6,6,6,10.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29843,1500920,1,4,6,6,6,6,6,11.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29844,1500783,1,4,6,6,6,6,6,11.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29845,1501011,1,1,6,6,6,6,6,11.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_ja.to_csv("../Database/Benesse/1571_ja.csv", index=False, encoding="utf-8-sig")

In [25]:
df_ja.to_parquet("../Database/Benesse/1571_ja.parquet", index=False, engine="pyarrow")